let numbers = []
console.log(numbers.length)
numbers.push(4)
console.log(numbers.length)
numbers.push(8)
console.log(numbers.length)
numbers.push(15)
console.log(numbers.length)
numbers.push(16)
console.log(numbers.length)
numbers.push(23)
console.log(numbers.length)
numbers.push(42)
console.log(numbers)
console.log(numbers.length)
